# Generated by Django 5.2.4 on 2025-10-17 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0011_alter_tool_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='category',
            field=models.CharField(choices=[('AI Art', 'AI Art'), ('AI Tools', 'AI Tools'), ('App Development', 'App Development'), ('Automation', 'Automation'), ('Blockchain', 'Blockchain'), ('Career', 'Career'), ('Cloud Computing', 'Cloud Computing'), ('Copywriting', 'Copywriting'), ('Cryptocurrency', 'Cryptocurrency'), ('Customer Support', 'Customer Support'), ('Cybersecurity', 'Cybersecurity'), ('Data Analysis', 'Data Analysis'), ('Deep Learning', 'Deep Learning'), ('Design', 'Design'), ('E-commerce', 'E-commerce'), ('Education', 'Education'), ('Entrepreneurship', 'Entrepreneurship'), ('Fitness', 'Fitness'), ('Food & Beverages', 'Food & Beverages'), ('Gaming', 'Gaming'), ('Generative AI', 'Generative AI'), ('Health', 'Health'), ('HR', 'HR'), ('Image Generation', 'Image Generation'), ('Investing', 'Investing'), ('IoT', 'IoT'), ('Legal', 'Legal'), ('Lifestyle', 'Lifestyle'), ('Machine Learning', 'Machine Learning'), ('Marketing', 'Marketing'), ('Mental Health', 'Mental Health'), ('Music', 'Music'), ('Networking', 'Networking'), ('News', 'News'), ('Personal Finance', 'Personal Finance'), ('Photography', 'Photography'), ('Product Management', 'Product Management'), ('Productivity', 'Productivity'), ('Real Estate', 'Real Estate'), ('Robotics', 'Robotics'), ('SEO', 'SEO'), ('Social Media', 'Social Media'), ('Sports', 'Sports'), ('Startups', 'Startups'), ('Travel', 'Travel'), ('UI/UX', 'UI/UX'), ('Video Editing', 'Video Editing'), ('Video Generation', 'Video Generation'), ('VR/AR', 'VR/AR'), ('Web Development', 'Web Development'), ('Writing', 'Writing')], default='AI Tools', max_length=50),
        ),
    ]
