# Generated by Django 5.2.4 on 2025-12-05 12:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0012_alter_tool_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tool',
            options={'ordering': ['-upvotes', '-created_at']},
        ),
        migrations.AddField(
            model_name='tool',
            name='company_info',
            field=models.TextField(blank=True, help_text='JSON formatted company info'),
        ),
        migrations.AddField(
            model_name='tool',
            name='cons',
            field=models.TextField(blank=True, help_text='Comma-separated cons'),
        ),
        migrations.AddField(
            model_name='tool',
            name='features',
            field=models.TextField(blank=True, help_text='JSON formatted features list'),
        ),
        migrations.AddField(
            model_name='tool',
            name='integrations',
            field=models.TextField(blank=True, help_text='Comma-separated integrations'),
        ),
        migrations.AddField(
            model_name='tool',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tool',
            name='last_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='long_description',
            field=models.TextField(blank=True, help_text='Extended description for SEO'),
        ),
        migrations.AddField(
            model_name='tool',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='tool',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='tool',
            name='pricing_info',
            field=models.TextField(blank=True, help_text='JSON formatted pricing details'),
        ),
        migrations.AddField(
            model_name='tool',
            name='pros',
            field=models.TextField(blank=True, help_text='Comma-separated pros'),
        ),
        migrations.AddField(
            model_name='tool',
            name='seo_title',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='tool',
            name='slug',
            field=models.SlugField(blank=True, unique=False),
        ),
        migrations.AddField(
            model_name='tool',
            name='social_links',
            field=models.TextField(blank=True, help_text='JSON formatted social links'),
        ),
        migrations.AddField(
            model_name='tool',
            name='success_score',
            field=models.PositiveIntegerField(default=0, help_text='0-100 tool quality score'),
        ),
        migrations.AddField(
            model_name='tool',
            name='tech_stack',
            field=models.CharField(blank=True, help_text='Technologies used', max_length=200),
        ),
        migrations.AddField(
            model_name='tool',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='use_cases',
            field=models.TextField(blank=True, help_text='Typical use cases'),
        ),
        migrations.AddField(
            model_name='tool',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='tool',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tool',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='shaurya1234512'),
        ),
        migrations.AddIndex(
            model_name='tool',
            index=models.Index(fields=['category', '-upvotes'], name='tools_tool_categor_83c0dc_idx'),
        ),
        migrations.AddIndex(
            model_name='tool',
            index=models.Index(fields=['pricing', '-views'], name='tools_tool_pricing_e58ba2_idx'),
        ),
        migrations.AddIndex(
            model_name='tool',
            index=models.Index(fields=['slug'], name='tools_tool_slug_f69786_idx'),
        ),
    ]
