# Generated by Django 5.2.4 on 2025-12-05 13:21

import tools.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0013_enhance_tool_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload tool icon/logo (JPG, PNG, GIF). Max 5MB. Automatically optimized.', null=True, storage=tools.storage.MediaStorage(), upload_to='tools/%Y/%m/'),
        ),
    ]
